### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by dmiedema**
This works for me (I think? Running `carthage build --no-skip-current`).
I don't know of a better way to support it since cocoapods is baked into the demo project. Definitely open to other ideas.

For anyone using Carthage if correct support could be verified with this branch that'd be super awesome.

cc @kazmasaurus, @danishin

### CODE REVIEW

**Comment by Ashton-W** [comment]
Looks good to me. Let's solve any problems as they come up

**Comment by iliaskarim** [comment]
here's what I get when I add `github "cruffenach/CRToast"` to my Cartfile and run `carthage bootstrap`:

```
Dependency "CRToast" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/cruffenach/CRToast/issues/new
```

**Comment by davbeck** [comment]
I'm also seeing that error:

```
*** Skipped building CRToast due to the error:
Dependency "CRToast" has no shared framework schemes for any of the platforms: iOS
```

**Comment by Ashton-W** [comment]
@davbeck I am able to run `carthage build --no-skip-current` from the latest `master`?

**Comment by davbeck** [comment]
I've been adding Carthage support to my projects lately and have had several cases where 'carthage build --no-skip-current' works but integrating it with another project fails. I think it has to do with files or schemes that don't get checked in to git.

**Comment by Ashton-W** [comment]
The schemes are definitely shared and checked in. Even creating a `Cartfile` with contents `github "cruffenach/CRToast"` is bootstrapping on my machine.

**Pull request merged**
