### PR TITLE
Complete Refactor

### PR DESCRIPTION
**Pull request by dmiedema**
This is a complete reorganization of the current file structure. In the process I had to make a few more things 'public' since all the implementations were in one file allowing for shared knowledge.

I don't know if this is something you're looking to do, however I would like to start the discussion about it. This PR supersedes all my other pull (https://github.com/cruffenach/CRToast/pull/122, https://github.com/cruffenach/CRToast/pull/121, https://github.com/cruffenach/CRToast/pull/120, https://github.com/cruffenach/CRToast/pull/115) requests as well as adds a few other features from other users that have mentioned changed in the issues (https://github.com/miwillhite/CRToast/commit/498a731fb818c3aa7e2e5cf2b6a5bb56c8befc9f, https://github.com/cruffenach/CRToast/pull/69). I'm not 100% sure the changes in https://github.com/cruffenach/CRToast/pull/69 are successful & still pass but thats another issue.

Is this something that you would like to do? I feel that it adds a few requested features as well as fixes a few bugs. Maybe not in the same way but I tried to stay consistent to the current codebase. [issues with the current code format have been brought up](https://github.com/cruffenach/CRToast/issues/124) so i felt that refactoring was a decent idea even if it does come at a slight loss of elegance.

This is a gargantuan PR to look over so I totally understand not being super stoked about seeing it :grin: sorry.

### CODE REVIEW

**Comment by dmiedema** [comment]
Hey @Ashton-W,

I was informed it'd be best to reach out to you in regard to this so I figured I'd ping you directly.
I'm not sure what your thoughts are on something like this. I know a massive refactor like this is a nightmare to deal with since it breaks anyones previous changes if they update & breaks anyone's previous pull requests in a nearly unfixable manor.

Personally I think its more approachable even though its I believe more lines of code and more files just because its more broken up but thats just me, I did it so I'm bias.

That said, are there any hopes of something this breaking getting merged in?
If not is there a middle ground that can be reached in regards to the massive change set.
Honestly I hate the idea of maintaining my own fork but I _can_ do it if it's necessary.

Cheers,
Daniel

**Comment by Ashton-W** [comment]
Hi @dmiedema,

I'm all for this change! Thanks for putting in the work, I understand the pain in creating large changes like this.

One thing I would ask is you look at the CI build https://travis-ci.org/cruffenach/CRToast/builds/45591782 for this PR, compilation is failing (at least on travis) for iOS 7.0 - 7.1

Regards

**Comment by dmiedema** [comment]
It looks like its in regards to https://github.com/dmiedema/CRToast/blob/refactor/CRToast/CRToastLayoutHelpers.h#L78-L79 which uses `UIUserInterfaceSizeClassRegular` & `UITraitCollection` to account for 6 plus in landscape's navigation bar being a different height than 3.5, 4 & 4.7" iPhones in landscape. :no_mouth: 

While it still _runs_ on iOS 7 since that path never executes, it requires the iOS 8 SDK to compile with those changes added. 

What would be the preferred way to fix it? While I don't really like the idea of ignoring the issue until the iOS 8 SDK is required for all submitted apps, that would be an option. Or would wrapping them in a wrapper that only is added in under iOS 8 SDK compilation be a better option?

**Comment by Ashton-W** [comment]
It's using an enum so I think the only choice is to mask it's use out with a SDK check macro.

**Comment by dmiedema** [comment]
Sorry for all the travis/commit/comment spam. I _think_ the latest commit should fix everything up. It works as far as i've tested but another quick once over would probably be beneficial to make sure I didn't overlook something.

**Comment by dmiedema** [comment]
Sorry again for the push/comment/travis spam. That should include all the changes and everything should be all good now :+1:

**Comment by dmiedema** [comment]
@Ashton-W 

Got all the tests passing & I'm done messing around with this - I've been working on providing a custom view but I'll wait for that for a separate PR as this one is big enough.

All the merge commits were my addition of Travis CI to my fork so I could stop spamming this PR with commits to run tests.

Any notes or requests on this or is it good to go?

**Comment by jadar** [comment]
I can update my PR for a custom view when you merge this, if you want.

**Comment by Ashton-W** [comment]
'Slide Over Status and Nav Bar' in the demo app seems to no longer do anything. Have we lost the animation type where a snapshot of the bar is animated?

**Comment by dmiedema** [comment]
We most definitely shouldn't have. I did include a change that made the snapshot configurable which may have had unintended consequences i hadn't noticed.

I'll look into this one

**Comment by dmiedema** [comment]
Looks like I only half implemented the change accidentally. I missed that use case so I hadn't noticed.

**Comment by dmiedema** [comment]
Sorry for all the travis spam -- I wasn't super keen on the change i made to fix the gravity in animation crash so I redid it this morning.

This reverts recent changes made to fix the crash in regards the gravity in animation.

Each toast now generates one notificationView and one statusBarView and returns the generated one instead of generating a new one on every access.
I'm currently not aware of any other consequences in regards to these changes as everything still sees to be working fine

This PR just keeps getting longer and longer making it look worse and worse and for that I apologize. I do like having the entire history to see the changes however it makes this just look massive.

**Comment by Ashton-W** [comment]
Merged. Let's deal with any issues as they come up

**Pull request merged**
